services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: ton
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 123ton123
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://n8n-qqko.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-qqko.onrender.com
      - key: N8N_PROTOCOL
        value: https

      # PostgreSQL config
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-d0la9kffte5s739audbg-a
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8ndb_3v2j
      - key: DB_POSTGRESDB_USER
        value: ton
      - key: DB_POSTGRESDB_PASSWORD
        value: 7TvjvhwYNrNcuLEs06i34IfPcUyHuAaw
      - key: DB_POSTGRESDB_SCHEMA
        value: public
