services:
  - type: web
    name: n8n
    runtime: docker          # ← was `env: docker`
    plan: starter
    branch: master
    dockerfilePath: ./Dockerfile

    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: ton
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 123ton123
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://n8n-qqko.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-qqko.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENCRYPTION_KEY
        value: 9f86d081884c7d659a2feaa0c55ad015
      - key: DB_TYPE
        value: sqlite            # switched from Postgres

    disk:
      name: n8n-data             # choose any unique name
      mountPath: /home/node/.n8n # where n8n stores its SQLite file
      sizeGB: 1                  # 1 GB is plenty for workflows
